server:
  port: 9000
spring:
  application:
    name: api-zuui
eureka:
  client:
    # eureka client刷新本地缓存时间,默认30s
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    # 超过这个时间没收到心跳就剔除这个服务，这个配置一般为服务刷新时间配置的三倍，默认90s
    lease-expiration-duration-in-seconds: 15
    # 服务刷新时间，默认30s
    lease-renewal-interval-in-seconds: 5

ribbon:
  #请求连接的超时时间，默认时间为1秒
  ConnectTimeout: 5000
  #请求处理的超时时间
  ReadTimeout: 5000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000
zuul:
  #统一入口的路由映射
  routes:
    order-service: /zuui-order/**
    product-service: /zuui-product/**
  #忽略以下服务，不能通过网关访问
  ignored-services: product-service,order-service
  #处理Http请求头为空的问题
  sensitive-headers:

