server:
  port: 8903
spring:
  application:
    name: order-service

  redis:
    database: 0
    host: 182.92.243.236
    port: 6379
    password:
    lettuce:
      pool:
        #连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 8
        #连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1
        #连接池中的最大空闲连接 默认 8
        max-idle: 8
        #连接池中的最小空闲连接 默认 0
        min-idle: 0

eureka:
  client:
    # eureka client刷新本地缓存时间,默认30s
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    # 超过这个时间没收到心跳就剔除这个服务，这个配置一般为服务刷新时间配置的三倍，默认90s
    lease-expiration-duration-in-seconds: 15
    # 服务刷新时间，默认30s
    lease-renewal-interval-in-seconds: 5

feign:
  hystrix:
    enabled: true
ribbon:
  #请求连接的超时时间，默认时间为1秒
  ConnectTimeout: 5000
  #请求处理的超时时间
  ReadTimeout: 5000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000
management:
  endpoints:
    web:
      exposure:
        include: "*"
