server:
  port: 8901

  zipkin:
    base-url: http://182.92.243.236:9411/
  sleuth:
    sampler:
      probability: 1
eureka:
  client:
    # eureka client刷新本地缓存时间,默认30s
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

  instance:
    # 超过这个时间没收到心跳就剔除这个服务，这个配置一般为服务刷新时间配置的三倍，默认90s
    lease-expiration-duration-in-seconds: 15
    # 服务刷新时间，默认30s
    lease-renewal-interval-in-seconds: 5

api:
 url: "priceApiURL"


